### ISSUE TITLE
best win tilling manager

### ISSUE THREAD

**Issue by Feeco-Li** [jpginc/windowsWindowTilingManager#1]
i have tried, many of windows window tilling managers, including bug.n/hashtwm/etc/many many as you name it. this is most simple and stable one. bug.n is more comprehensive but, always some issues with chrome and  terminals, and, you have to add other window class yourself. hashtwm have some threading problems. rest of them are not smart enough, since you have to configure the grids manually.

only this wwtm is simple and clear and stable, this is amazing, i do not know why, so few people know this, many just cuz name is too normal.

paste some shortcuts from ahk commuity, and, wish author could add some more documentation about these scripts. what you have done, is so awsome. merry christmas and year, greeting from canada.

windows key + g: reset the tilining of all windows again
windows key + t: stop/start tiling the active window
windows key + j: move the middle split left
windows key + k: move the middle split right
windows key + shift + j: rotate the windows' position around left
windows key + shift + k: rotate the windows' position around right

**Comment by jpginc** [comment]
I'm glad you like it :-). I didn't document this one because I didn't think it was in a state where it was useful enough for people to use, evidently i was wrong. I'll add a readme with a couple of instructions. Let me know if there is a feature you want implemented and I'll try to get it done
